Getting Started (Rough Draft)
UWB-ACM/Hackathon-Docs-2020 pull request #14
Opened 2020-02-07 22:14 UTC by RyanRussell00

I added a folder called 'getting_started' and it has 3 files:

- `Collaboration.md` =  Specifies how the participants can communicate and work with each other, as well as communicate with mentors
- `Software.md` = Accounts and Software that should be set up prior to the Hackathon
- `Preparation_List.md` = Things to do before the Hackathon and what to bring. It contains some useful resources to help prepare for your first hackathon.

By no means is this the final draft, please share ideas on what else we should add to any of these files, or if we should add any new files completely.

2020-02-07 23:05 UTC, etcadinfinitum requested changes
Good start, but there's a few things that need to be changed

1. I appreciate the directory organization efforts, but the [Jekyll collections](https://jekyllrb.com/docs/collections/) schema that we are using requires all of the docs we want on the page to be dropped in the `_docs` folder, no subfolders. _I really appreciate the intent though :D_
2. Again, for Jekyll, we need the [front matter](https://jekyllrb.com/docs/front-matter/) at the top of the file. [The front matter we need for each file is detailed here.](https://raw.githubusercontent.com/UWB-ACM/Hackathon-Docs-2020/master/template.md)

2020-02-07 23:05 UTC, etcadinfinitum commented on getting_started/Collaboration.md
> +## **Collaborative Cloud**
Not necessary imo, but feel free to prove me wrong

2020-02-07 23:05 UTC, etcadinfinitum commented on getting_started/Collaboration.md
> +# **Table of Contents**
Missing front matter for Jekyll generation; I'll demonstrate what I mean at the meeting today

2020-02-07 23:05 UTC, etcadinfinitum commented on getting_started/Preparation_List.md
> +Whether you're a hackathon newbie or a 10x "Unicorn",
Erica is working on the writeup for this file; see #5

2020-02-07 23:05 UTC, etcadinfinitum commented on getting_started/Software.md
> +#PLEASE ENSURE YOU HAVE INSTALLED AND SETUP THE FOLLOWING SOFTWARE AND ACCOUNTS
This file _might_ be redundant, but we can discuss pros/cons as a group

2020-02-07 23:20 UTC, RyanRussell00 commented
-Add how to setup an AWS account and get free credits

2020-02-08 07:56 UTC, etcadinfinitum commented
> -Add how to setup an AWS account and get free credits

See https://github.com/UWB-ACM/Hackathon-Docs-2020/blob/master/_docs/cloud_account_setup.md; link to that if you feel it necessary

2020-02-14 22:12 UTC, RyanRussell00 commented on getting_started/Collaboration.md
> +## **Collaborative Cloud**
Removed

2020-02-14 22:12 UTC, RyanRussell00 commented on getting_started/Preparation_List.md
> +Whether you're a hackathon newbie or a 10x "Unicorn",
Removed

2020-02-14 22:13 UTC, RyanRussell00 commented on getting_started/Software.md
> +#PLEASE ENSURE YOU HAVE INSTALLED AND SETUP THE FOLLOWING SOFTWARE AND ACCOUNTS
I agree, I just saw the file with all the info for this.

2020-02-14 22:15 UTC, RyanRussell00 commented on getting_started/Collaboration.md
> +# **Table of Contents**
Added the front matter, see latest push

2020-02-17 20:35 UTC, etcadinfinitum approved these changes
See suggested changes. Otherwise, looks fine. Thanks!

2020-02-17 20:35 UTC, etcadinfinitum commented on _docs/collaboration.md
> +**TODO** Insert information about how to share AWS accounts and give permissions to others.
```suggestion
Check out [our guide on choosing a cloud provider](https://docs.uwbhacks.com/cloud_setup.html) to pick a cloud platform to use for your project.

When you're ready, you can add users and give them permissions to use account services for your project. You can choose to share your administrator credentials, or you can create user accounts and give them specific permissions. When creating user accounts, you can follow the instructions for [AWS](https://docs.aws.amazon.com/marketplace/latest/userguide/marketplace-management-portal-user-access.html), [GCP](https://cloud.google.com/appengine/docs/standard/go/access-control#developers), and [Azure](https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/add-users-azure-active-directory).
```

2020-02-17 20:35 UTC, etcadinfinitum commented on _docs/collaboration.md
> +order: 1
This will appear after "Cloud Provider Setup", which makes sense to me.
```suggestion
order: 6
```

2020-02-18 20:43 UTC, merged