Added steps for setting up IAM, Lambda, API Gateway
UWB-ACM/Hackathon-Docs-2020 pull request #32
Opened 2020-03-30 02:51 UTC by RyanRussell00

Added step-by-step instructions on reproducing the IAM, Lambda and API Gateway used for the crowfacts project.

Still need to do:
- How to connect your front-end to API Gateway
- What is CORS and how to use it

2020-04-02 03:00 UTC, etcadinfinitum requested changes
General comments:

- Much of this content is written as if the reader is going to recreate this project in its entirety, instead of generalizing the problems we encountered and using the takeaways & resources to work on a different project. **We want to provide insight about how the project is structured; we don't need a step-by-step set of instructions.**
- Step by step processes for setting up permissions (and probably other things) should be directed to an official tutorial. This will help generalize _this_ project for a wider audience.
- If you aren't directing to official tutorials or AWS docs, at a minimum, you should include screenshots. A text description ("the big orange button in the corner") isn't nearly as useful as visualizing where the GUI object is that you're interested in. _It also isn't as compelling for the average reader._

This is a surprising amount of detail, and seems unnecessary considering the volume of literature that's out on the internet about using AWS, Dynamo, API Gateway, and Lambda. Think of a water balloon of information, not a dunk tank.

I recommend looking at the feelgood page and Anish's [PR](https://github.com/UWB-ACM/Hackathon-Docs-2020/pull/31) in detail to get more of an idea of what information is detailed step by step versus what concepts are named and then linked externally.

2020-04-02 03:00 UTC, etcadinfinitum commented on _docs/crowfacts.md
> +2. Head over to [API Gateway service](https://us-west-2.console.aws.amazon.com/apigateway/main/apis?region=us-west-2).
Nope, do not put the console URL in here -- for one, not everybody will have an AWS account to follow along, and secondly, not everyone will be using the US-Oregon region, and creating different product instances across regions can have unintended negative consequences (like being unable to communicate between services across regions).

2020-04-02 03:00 UTC, etcadinfinitum commented on _docs/crowfacts.md
> +1. Go to the [IAM services](https://console.aws.amazon.com/iam/home?region=us-west-2#/home) page and select "roles" on the left menu, and click on the blue "Create role" button.
Nope, do not put the console URL in here -- for one, not everybody will have an AWS account to follow along, and secondly, not everyone will be using the US-Oregon region, and creating different product instances across regions can have unintended negative consequences (like being unable to communicate between services across regions).

2020-04-02 03:00 UTC, etcadinfinitum commented on _docs/crowfacts.md
> +```
Recommend _not_ putting code in here; that's what the [CrowFacts repository](https://github.com/UWB-ACM/crowfacts) is for.

If you _must_ put code in here, make sure to do syntax highlighting, lest the code be a block of monocolored text which doesn't look like code.

````suggestion
```python3
````

2020-04-02 03:00 UTC, etcadinfinitum commented on _docs/crowfacts.md
> +		return e.response['Error']['Message']
Indentation here looks visually wrong -- Python is very particular about this. If it wouldn't run in production, we shouldn't put in in our docs.

2020-04-02 03:00 UTC, etcadinfinitum commented on _docs/crowfacts.md
> +	except Exception as e:
Why so much whitespace? This becomes hard to read. It's a pretty particular thing, but there's no good reason for whitespace to be between a comment and the code the comment is referring to, at a bare minimum, imo. If I were you, I'd scrap all unnecessary line breaks.

2020-04-02 03:00 UTC, etcadinfinitum commented on _docs/crowfacts.md
> +	except Exception as e:
Generic exceptions are always suspicious. Recommend [reading this, and all the way to the bottom.](https://github.com/boto/boto3/issues/1262#issuecomment-467465203)

2020-04-03 17:27 UTC, closed without merging

2020-04-03 17:27 UTC, RyanRussell00 commented
@etcadinfinitum Thanks for the review, I will go ahead and fix it and resubmit the PR.