Azure Resources Page
UWB-ACM/Hackathon-Docs-2020 pull request #46
Opened 2020-04-10 23:28 UTC by anishprasad01

Still in-progress, but wanted to get some feedback now. SDK, Tools, and Tutorial links that I think will be useful are already done. Helpful Tidbits needs work.

2020-04-13 07:04 UTC, Chris-Johnston requested changes
Looks good so far, just a few comments.

One thing I would include would be a link to docs.microsoft.com for all thing Azure/.NET/etc.

2020-04-13 07:04 UTC, Chris-Johnston commented on _docs/azure_resources.md
> +- [Unified SDKs](https://azure.github.io/azure-sdk/releases/latest/index.html#java-packages) available for: .NET, Java, Python, TypeScript/JavaScript
```suggestion
- [Unified SDKs](https://azure.github.io/azure-sdk/releases/latest/index.html) available for: .NET, Java, Python, TypeScript/JavaScript
```
might as well link using the top of the page

2020-04-13 07:04 UTC, Chris-Johnston commented on _docs/azure_resources.md
> +- [Azure Visual Studio](https://azure.microsoft.com/en-us/products/visual-studio/)
seems like a redundant link?

2020-04-13 07:04 UTC, Chris-Johnston commented on _docs/azure_resources.md
> +- Most resources on Azure require supporting resources to be provisioned alongside the main offering. For example, provisioning a VM will also require a Storage Account, Virtual Networking, etc. Thes
To add to this, this is why "resource groups" are a thing. Under a subscription you can create many resource groups that represent individual projects. When it comes time to delete resources, you can just delete the whole resource group.

2020-04-13 07:04 UTC, Chris-Johnston commented on _docs/azure_resources.md
> +- **Security Principals** are objects that represent the entity that must be granted permissions. There are four tupes of supportal prinipals: users, groups, service prinicpals, and managed identitie
```suggestion
- **Security Principals** are objects that represent the entity that must be granted permissions. There are four types of security principals: users, groups, service principals, and managed identities. See the documentation page for more info on what each type of security principal is for.
```

2020-04-13 07:04 UTC, Chris-Johnston commented on _docs/feelgood.md
> +- **Schedule expression** is where you define the time interval that the function should be triggered at. FeelGood uses cron syntax identical to the syntax used to schedule recurring jobs in native U
```suggestion
- **Schedule expression** is where you define the time interval that the function should be triggered at. FeelGood uses cron syntax identical to the syntax used to schedule recurring jobs in native Unix systems; a good reference on cron syntax we found useful is available [here](https://www.adminschoice.com/crontab-quick-reference). Cron syntax uses UTC time. In FeelGood, the trigger uses the cron syntax `cron(0 18 * * ? *)`, which means every day at 10 AM PST/11 AM PDT. We recommend looking up a converter from UTC to your timezone. Saving and enabling this trigger will run the function at the specified time. AWS has a good explainer on creating CloudWatch Events Rules [here](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/Create-CloudWatch-Events-Scheduled-Rule.html). AWS also has a good document on how to [setup CloudWatch triggers for Lambda using cron syntax](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html).
```

2020-04-13 23:35 UTC, anishprasad01 commented on _docs/azure_resources.md
> +- [Unified SDKs](https://azure.github.io/azure-sdk/releases/latest/index.html#java-packages) available for: .NET, Java, Python, TypeScript/JavaScript
Good catch, thanks

2020-04-13 23:36 UTC, anishprasad01 commented on _docs/azure_resources.md
> +- [Azure Visual Studio](https://azure.microsoft.com/en-us/products/visual-studio/)
Yeah, definitely

2020-04-14 00:28 UTC, etcadinfinitum approved these changes
LGTM!

2020-04-14 00:28 UTC, etcadinfinitum commented on _docs/azure_resources.md
> +- **Security Principals** are objects that represent the entity that must be granted permissions. There are four types of security principals: users, groups, service principals, and managed identitie
Add embedded link to docs page for good measure
```suggestion
- **Security Principals** are objects that represent the entity that must be granted permissions. There are four types of security principals: users, groups, service principals, and managed identities. See the [documentation page](https://docs.microsoft.com/en-us/azure/role-based-access-control/overview#security-principal) for more info on what each type of security principal is for.
```

2020-04-14 05:21 UTC, Chris-Johnston approved these changes
:shipit:

2020-04-14 05:42 UTC, merged