Cloudfaq
UWB-ACM/Hackathon-Docs-2020 pull request #7
Opened 2020-01-31 23:28 UTC by anishprasad01

In-progress work on the Cloud FAQ. Links pending and all sections require more detail. and revision.

2020-01-31 23:36 UTC, etcadinfinitum requested changes
Looks fine at first glance, will review more later

2020-01-31 23:36 UTC, etcadinfinitum commented on _docs/whatiscloud.md
> +# What is the Cloud? OR Cloud Services FAQ
Hmmm this title should be one or the other...
```suggestion
# Cloud Services FAQ
```

2020-02-02 23:44 UTC, etcadinfinitum approved these changes
Looks like a great start in my opinion! I added a few suggested changes, and we will have to revisit external links as the pages get added. If you want to create corresponding issues in this repo for external links and merge as-is, that sounds fine to me.

2020-02-02 23:44 UTC, etcadinfinitum commented on .gitignore
> +_docs/~$atiscloud.md
Make this generic; `.gitignore` allows for [shell-style wildcard matching](https://git-scm.com/docs/gitignore).
```suggestion
_docs/~$*.md
```

2020-02-02 23:44 UTC, etcadinfinitum commented on _docs/whatiscloud.md
> +Almost anything you can dream of. Cloud providers are constantly improving and adding to their offerings. A good place to start would be to take a simple application that you could run locally, such
To do: replace [LINK HERE] with link to a docs page. Feel free to add a link to an internal doc page or an external page.

2020-02-02 23:44 UTC, etcadinfinitum commented on _docs/whatiscloud.md
> +* GCP Documentation [LINK]
To do: External links. We can revisit this as the docs pages get more fleshed out.

2020-02-02 23:44 UTC, etcadinfinitum commented on _docs/whatiscloud.md
> +Refer to [INSERT LINK HERE] to learn how you can get your hands on some free student credits!
```suggestion
Refer to [our guide on cloud providers](_docs/cloud_account_setup.md) to learn how you can get your hands on some free student credits!
```

2020-02-02 23:53 UTC, etcadinfinitum commented on _docs/whatiscloud.md
> +Refer to [INSERT LINK HERE] to learn how you can get your hands on some free student credits!
Note: I'm not sure how the internal linking will work just yet; it might have to be linked to the `.html` permalink address instead of the `.md` file

2020-02-03 18:09 UTC, huyn8 approved these changes
Checked for typo, errors, etc. and it's looking good so far. I like how there are links to examples. I personally love examples because they help to explain a lot. So the more examples the better.

2020-02-03 20:25 UTC, merged